session TotalViper = "HOL" +
  sessions
    "HOL-Eisbach"
  directories
    "foundational_boogie/BoogieLang"
    "viper-semantics"
  theories
    TotalViperState
    TotalStateUtil
    TotalExpressions
    TotalSemantics
    TotalSemProperties
    TotalUtil
    ViperBoogieAbsValueInst
    ViperBoogieBasicRel
    ViperBoogieFunctionInst
    ViperBoogieTranslationInterface
    ViperBoogieRelUtil
    TotalViperHelperML
    CPGHelperML
    ExpRel
    ExpRelML
    ExprWfRel
    ExprWfRelML
    StmtRel
    InhaleRelML
    ExhaleRelML
    StmtRelML
    ViperBoogieEndToEnd
    ViperBoogieEndToEndML
