session TotalViper = Viper +
  sessions
    "HOL-Eisbach"
    "Boogie_Lang"
  theories
    TotalViperState
    TotalStateUtil
    TotalExpressions
    TotalSemantics
    TotalSemProperties
    TotalUtil
    ViperBoogieAbsValueInst
    ViperBoogieBasicRel
    ViperBoogieFunctionInst
    ViperBoogieTranslationInterface
    ViperBoogieRelUtil
    TotalViperHelperML
    CPGHelperML
    ExpRel
    ExpRelML
    ExprWfRel
    ExprWfRelML
    StmtRel
    InhaleRelML
    ExhaleRelML
    StmtRelML
    ViperBoogieEndToEnd
    ViperBoogieEndToEndML
