session TotalViper = Viper +
  sessions
    "HOL-Eisbach"
    "Boogie_Lang"
  theories
    TotalViperState
    TotalStateUtil
    TotalConsistency
    TotalExpressions
    TotalSemantics
    TotalSemProperties
    TotalUtil
    ViperBoogieAbsValueInst
    ViperBoogieBasicRel
    ExpRel
    ExpRelML
    ExprWfRel
    ExprWfRelML
    ExpProofGenTest
